### ISSUE TITLE
Official Azure Maps API Client

### ISSUE THREAD

**Issue by fabich** [microsoft/Maps#3]
Hi @rbrundritt

Is Microsoft releasing an official API client for Azure Maps?

**Comment by fabich** [comment]
the only .net client that we can find is the one recommend by @microsoft
https://github.com/microsoft/Maps/blob/master/AzureMaps.md#tools-and-extensions
[perfahlen/AzureMapsRestServices](https://github.com/perfahlen/AzureMapsRestServices)

but this client is missing endpoints, has major bugs (some with PRs for these bugs that are open since many months) and undocumented releases.

not having an official client makes using Azure Maps quite annoying...

**Comment by rbrundritt** [comment]
The Azure Maps team is planning to release an official .NET client library later this year. 

Also worth noting that you can generate a .NET library using [AutoREST ](https://github.com/Azure/AutoRest) and the [data plane](https://github.com/Azure/azure-rest-api-specs/tree/d70b7cc88d45ef55484c26251f4d5497f12b5dad/specification/maps)

**Comment by rbrundritt** [comment]
Closing as this was released last year: https://learn.microsoft.com/en-us/azure/azure-maps/rest-sdk-developer-guide
