### ISSUE TITLE
Problem with reverse geocoding using D

### ISSUE THREAD

**Issue by alidavoudian** [microsoft/Maps#6]
As the code below shows, some of the addresses are not perfectly geocodes:

# Create a dataframe that's tied to it's column names
df = spark.createDataFrame(((
    (45.32202, -75.83875),
    (47.62039, -122.34928),
    (45.37032, -75.70161),
    (45.3702793, -75.7037331),
    (45.28471, -75.73897),
    (48.85607, 2.29833)
  )), StructType([StructField("lat", DoubleType()), StructField("lon", DoubleType())]))

# Run the Azure Maps geocoder to enhance the data with location data
rev_geocoder = (ReverseAddressGeocoder()
    .setSubscriptionKey(azureMapsKey)
    .setLatitudeCol("lat")
    .setLongitudeCol("lon")
    .setOutputCol("output"))

# Show the results of your text query in a table format
display(rev_geocoder.transform(FixedMiniBatchTransformer().setBatchSize(10).transform(df)).select(col("*"),
      col("output.response.addresses").getItem(0).getField("address").getField("freeformAddress").alias("freeformAddress"),
      col("output.response.addresses").getItem(0).getField("address").getField("country").alias("country")
    ).drop("output"))

The results are as below:

![image](https://user-images.githubusercontent.com/58340597/175979171-8cf8e582-dceb-47fc-aad8-20493d2ddbd3.png)

lat	lon	ReverseAddressGeocoder_da64c6411c23_error	freeformAddress	country
[45.32202]	[-75.83875]		["25 Fitzgerald Road, Nepean ON K2H 1C3"]	["Canada"]
[47.62039]	[-122.34928]		["400 Broad Street, Seattle, WA 98109"]	["United States"]
[45.37032]	[-75.70161]			
[45.3702793]	[-75.7037331]			
[45.28471]	[-75.73897]			
[48.85607]	[2.29833]		["Place Jacques Rueff, 75007 Paris"]	["France"]

**Comment by rbrundritt** [comment]
This is not a support channel. Please ask your question either in the [Azure Maps forum](https://docs.microsoft.com/en-us/answers/topics/azure-maps.html) or contact the Azure support team.
